name: Docker Image Build and Deploy

on:
  push:
    branches: [ "version1" ]
  pull_request:
    branches: [ "version1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env
          echo ".env file created"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t tsmsanket18/hrms_app_frontend:latest .
          docker push tsmsanket18/hrms_app_frontend:latest

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.TEST1 }}" > TSMHRMS.pem
          chmod 600 TSMHRMS.pem
          ssh -o StrictHostKeyChecking=no -i TSMHRMS.pem ubuntu@ec2-44-196-49-134.compute-1.amazonaws.com << 'EOF'
            # Authenticate Docker
            sudo docker login -u tsmsanket18 -p ${{ secrets.DOCKER_PASSWORD }}
            
            # Pull and replace the container
            sudo docker pull tsmsanket18/hrms_app_frontend:latest
            sudo docker stop frontend || true
            sudo docker rm frontend || true
            sudo docker run -d --name frontend -p 8080:80 tsmsanket18/hrms_app_frontend:latest
            
            # Clean up old images
            sudo docker image prune -af
          EOF
